<Project Sdk="Dalamud.NET.Sdk/12.0.2">
    <PropertyGroup>
        <Version>1.3.1.2</Version>
        <Description>Get aurally rewarded when you get commended on duties.</Description>
        <PackageProjectUrl>https://github.com/jkchen2/ffxiv-congratulations-plugin</PackageProjectUrl>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="NAudio.Wasapi" Version="2.2.1"/>
    </ItemGroup>

    <Target Name="CopyResources" AfterTargets="Build">
        <ItemGroup>
            <GetFiles Include="$(ProjectDir)\Sounds\*"/>
        </ItemGroup>
        <Copy SourceFiles="%(GetFiles.Identity)" DestinationFolder="$(OutDir)\Sounds"/>
    </Target>
</Project>
